name: Generate cells docs

on:
    push:
    pull_request:

jobs:

  generate-cells:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate cells READMEs
        run: |
          SUBMODULE_VERSION=latest make submodules -j3 || make submodules -j1

          make env

          source env/conda/bin/activate skywater-pdk-scripts

          git submodule foreach 'git checkout master'
          scripts/python-skywater-pdk/skywater_pdk/cell_list.py libraries/*/latest/
          scripts/python-skywater-pdk/skywater_pdk/cell_readme_generate.py libraries/*/latest/cells/*
          git submodule foreach 'git add .'
          export DAT=`date +"%Y-%m-%d %k:%M"`

          # TODO replace below with appropriate credentials
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"
          git submodule foreach 'git commit -m "$DAT"'
